"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { useRouter } from "next/navigation";
import type { AnomalyExplanation } from "@/lib/api";

interface AnomalyDetailDialogProps {
  anomaly: AnomalyExplanation | null;
  onClose: () => void;
}

export function AnomalyDetailDialog({ anomaly, onClose }: AnomalyDetailDialogProps) {
  const router = useRouter();

  return (
    <Dialog.Root open={anomaly != null} onOpenChange={(open) => !open && onClose()}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-50 bg-black/40" />
        <Dialog.Content
          className="fixed top-1/2 left-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-lg border p-0 shadow-lg focus:outline-none"
          style={{ borderColor: "var(--gridline)", backgroundColor: "var(--chart-surface)" }}
        >
          {anomaly && (
            <div className="max-h-[80vh] overflow-y-auto p-5">
              <div className="mb-4 flex items-start justify-between gap-4">
                <div>
                  <Dialog.Title asChild>
                    <h2 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
                      {anomaly.region} — {anomaly.timestamp}
                    </h2>
                  </Dialog.Title>
                  <Dialog.Description asChild>
                    <p className="mt-0.5 text-xs" style={{ color: "var(--text-secondary)" }}>
                      Severity {anomaly.severity_score.toFixed(4)}
                      {anomaly.anomaly_type ? ` · ${anomaly.anomaly_type}` : ""}
                    </p>
                  </Dialog.Description>
                </div>
                <Dialog.Close asChild>
                  <button
                    type="button"
                    aria-label="Close"
                    className="shrink-0 rounded-md p-1 text-sm"
                    style={{ color: "var(--text-muted)" }}
                  >
                    ✕
                  </button>
                </Dialog.Close>
              </div>

              <div
                className="mb-4 rounded-md border p-3 text-xs"
                style={{
                  borderColor: "var(--diverging-up)",
                  backgroundColor: "var(--diverging-mid)",
                  color: "var(--text-secondary)",
                }}
              >
                This explanation is a hypothesis generated by an LLM agent for human review —
                not a diagnosis, no automated action has been taken.
              </div>

              <section className="mb-4">
                <h3 className="mb-1 text-xs font-semibold" style={{ color: "var(--text-primary)" }}>
                  Explanation
                </h3>
                <p className="text-sm" style={{ color: "var(--text-secondary)" }}>
                  {anomaly.explanation ?? "No explanation available for this anomaly."}
                </p>
              </section>

              <section className="mb-4">
                <h3 className="mb-1 text-xs font-semibold" style={{ color: "var(--text-primary)" }}>
                  Recommended action
                </h3>
                <p className="text-sm" style={{ color: "var(--text-secondary)" }}>
                  {anomaly.recommendation ?? "No recommendation available for this anomaly."}
                </p>
              </section>

              {anomaly.citations.length > 0 && (
                <section className="mb-5">
                  <h3 className="mb-1 text-xs font-semibold" style={{ color: "var(--text-primary)" }}>
                    Cited sources
                  </h3>
                  <ul className="list-inside list-disc text-sm" style={{ color: "var(--text-secondary)" }}>
                    {anomaly.citations.map((citation) => (
                      <li key={citation}>{citation}</li>
                    ))}
                  </ul>
                </section>
              )}

              <div className="flex justify-end gap-2 border-t pt-4" style={{ borderColor: "var(--gridline)" }}>
                <Dialog.Close asChild>
                  <button
                    type="button"
                    className="rounded-md border px-3 py-1.5 text-sm"
                    style={{ borderColor: "var(--gridline)", color: "var(--text-secondary)" }}
                  >
                    Close
                  </button>
                </Dialog.Close>
                <button
                  type="button"
                  disabled={anomaly.id == null}
                  onClick={() => {
                    if (anomaly.id != null) router.push(`/anomalies/${anomaly.id}`);
                  }}
                  className="rounded-md px-3 py-1.5 text-sm font-medium text-white disabled:opacity-50"
                  style={{ backgroundColor: "var(--series-accent)" }}
                >
                  View full details →
                </button>
              </div>
            </div>
          )}
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
