import Link from "next/link";
import { notFound } from "next/navigation";
import { getAnomalyById } from "@/lib/api";

export default async function AnomalyDetailPage(
  props: PageProps<"/anomalies/[id]">,
) {
  const { id } = await props.params;
  const anomalyId = Number(id);

  if (!Number.isInteger(anomalyId)) {
    notFound();
  }

  let anomaly;
  try {
    anomaly = await getAnomalyById(anomalyId);
  } catch {
    notFound();
  }

  const featureEntries = Object.entries(anomaly.contributing_features);

  return (
    <div className="min-h-screen bg-zinc-50 px-6 py-10 dark:bg-black sm:px-10">
      <main className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="mb-6 inline-block text-sm text-zinc-600 hover:text-zinc-950 dark:text-zinc-400 dark:hover:text-zinc-50"
        >
          ← Back to recent anomalies
        </Link>

        <header className="mb-6">
          <h1 className="text-2xl font-semibold text-zinc-950 dark:text-zinc-50">
            {anomaly.region} — {anomaly.timestamp}
          </h1>
          <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
            Severity score: {anomaly.severity_score.toFixed(4)}
            {anomaly.anomaly_type ? ` · Type: ${anomaly.anomaly_type}` : ""}
          </p>
        </header>

        <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-300">
          This explanation is a hypothesis generated by an LLM agent for human review — it
          is not a diagnosis and no automated action has been taken.
        </div>

        <section className="mb-6 rounded-lg border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900">
          <h2 className="mb-2 text-sm font-semibold text-zinc-950 dark:text-zinc-50">
            Explanation
          </h2>
          <p className="whitespace-pre-wrap text-sm text-zinc-700 dark:text-zinc-300">
            {anomaly.explanation ?? "No explanation available for this anomaly."}
          </p>
        </section>

        <section className="mb-6 rounded-lg border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900">
          <h2 className="mb-2 text-sm font-semibold text-zinc-950 dark:text-zinc-50">
            Recommended action
          </h2>
          <p className="text-sm text-zinc-700 dark:text-zinc-300">
            {anomaly.recommendation ?? "No recommendation available for this anomaly."}
          </p>
        </section>

        {anomaly.citations.length > 0 && (
          <section className="mb-6 rounded-lg border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900">
            <h2 className="mb-2 text-sm font-semibold text-zinc-950 dark:text-zinc-50">
              Cited sources
            </h2>
            <ul className="list-inside list-disc text-sm text-zinc-700 dark:text-zinc-300">
              {anomaly.citations.map((citation) => (
                <li key={citation}>{citation}</li>
              ))}
            </ul>
          </section>
        )}

        {featureEntries.length > 0 && (
          <section className="rounded-lg border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900">
            <h2 className="mb-2 text-sm font-semibold text-zinc-950 dark:text-zinc-50">
              Contributing features
            </h2>
            <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm sm:grid-cols-3">
              {featureEntries.map(([key, value]) => (
                <div key={key}>
                  <dt className="text-zinc-500 dark:text-zinc-500">{key}</dt>
                  <dd className="font-medium text-zinc-950 dark:text-zinc-50">
                    {value.toFixed(2)}
                  </dd>
                </div>
              ))}
            </dl>
          </section>
        )}
      </main>
    </div>
  );
}
