import Link from "next/link";
import { notFound } from "next/navigation";
import { getAnomalyById } from "@/lib/api";
import { FeatureComparisonChart } from "@/components/FeatureComparisonChart";
import { DeviationStatTile } from "@/components/DeviationStatTile";

export default async function AnomalyDetailPage(
  props: PageProps<"/anomalies/[id]">,
) {
  const { id } = await props.params;
  const anomalyId = Number(id);

  if (!Number.isInteger(anomalyId)) {
    notFound();
  }

  let anomaly;
  try {
    anomaly = await getAnomalyById(anomalyId);
  } catch {
    notFound();
  }

  const featureEntries = Object.entries(anomaly.contributing_features);

  return (
    <div
      className="min-h-screen px-6 py-10 sm:px-10"
      style={{ backgroundColor: "var(--background)" }}
    >
      <main className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="mb-6 inline-block text-sm hover:underline"
          style={{ color: "var(--text-secondary)" }}
        >
          ← Back to recent anomalies
        </Link>

        <header className="mb-6">
          <h1 className="text-2xl font-semibold" style={{ color: "var(--text-primary)" }}>
            {anomaly.region} — {anomaly.timestamp}
          </h1>
          <p className="mt-1 text-sm" style={{ color: "var(--text-secondary)" }}>
            Severity score: {anomaly.severity_score.toFixed(4)}
            {anomaly.anomaly_type ? ` · Type: ${anomaly.anomaly_type}` : ""}
          </p>
        </header>

        <div
          className="mb-6 rounded-lg border p-4 text-sm"
          style={{ borderColor: "var(--diverging-up)", backgroundColor: "var(--diverging-mid)", color: "var(--text-primary)" }}
        >
          This explanation is a hypothesis generated by an LLM agent for human review — it
          is not a diagnosis and no automated action has been taken.
        </div>

        <section
          className="mb-6 rounded-lg border p-5"
          style={{ borderColor: "var(--gridline)", backgroundColor: "var(--chart-surface)" }}
        >
          <h2 className="mb-2 text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
            Explanation
          </h2>
          <p className="whitespace-pre-wrap text-sm" style={{ color: "var(--text-secondary)" }}>
            {anomaly.explanation ?? "No explanation available for this anomaly."}
          </p>
        </section>

        <section
          className="mb-6 rounded-lg border p-5"
          style={{ borderColor: "var(--gridline)", backgroundColor: "var(--chart-surface)" }}
        >
          <h2 className="mb-2 text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
            Recommended action
          </h2>
          <p className="text-sm" style={{ color: "var(--text-secondary)" }}>
            {anomaly.recommendation ?? "No recommendation available for this anomaly."}
          </p>
        </section>

        {anomaly.citations.length > 0 && (
          <section
            className="mb-6 rounded-lg border p-5"
            style={{ borderColor: "var(--gridline)", backgroundColor: "var(--chart-surface)" }}
          >
            <h2 className="mb-2 text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
              Cited sources
            </h2>
            <ul className="list-inside list-disc text-sm" style={{ color: "var(--text-secondary)" }}>
              {anomaly.citations.map((citation) => (
                <li key={citation}>{citation}</li>
              ))}
            </ul>
          </section>
        )}

        {featureEntries.length > 0 && (
          <section
            className="mb-6 rounded-lg border p-5"
            style={{ borderColor: "var(--gridline)", backgroundColor: "var(--chart-surface)" }}
          >
            <h2 className="mb-3 text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
              Demand vs. baseline
            </h2>
            <FeatureComparisonChart
              actualValue={anomaly.contributing_features.value ?? 0}
              rollingMean={anomaly.contributing_features.rolling_mean_24h ?? 0}
            />
          </section>
        )}

        {"deviation_from_last_week" in anomaly.contributing_features && (
          <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
            <DeviationStatTile
              deviationMw={anomaly.contributing_features.deviation_from_last_week}
            />
            <div
              className="rounded-lg border p-4 text-sm"
              style={{ borderColor: "var(--gridline)", backgroundColor: "var(--chart-surface)" }}
            >
              <p style={{ color: "var(--text-muted)" }}>Hour of day / day of week</p>
              <p className="mt-1 font-medium" style={{ color: "var(--text-primary)" }}>
                {anomaly.contributing_features.hour_of_day}:00 ·{" "}
                {
                  ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][
                    anomaly.contributing_features.day_of_week
                  ]
                }
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
